config/routes.rb
Library::Application.routes.draw do

  get "users/new"
  resources :books do
    member do
      post 'lend', controller: 'loans', action: 'lend'
    end
  end

  resources :users
  

  resources :sessions, only: [:new, :create, :destroy]
  resources :loans, only: [:create, :destroy, :index, :update]
  
  root 'static_pages#home'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/signup', to: 'users#new', via: 'get'

  match '/signin', to: 'sessions#new', via: 'get'
  match '/signin', to: 'sessions#create', via: 'post'
  match '/signout', to: 'sessions#destroy', via: 'delete'

match '/search', to: 'books#index', via: 'get'
match '/search_user', to: 'users#index', via: 'get'

  

  

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	@books = Book.all 
  end

  def help
  end
  
  def about
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_conteudo.html.erb
Conteudo Aqui

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<h1>About Us</h1>
<p>
  The <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  is a project to make a book and screencasts to teach web development
  with <a href="http://rubyonrails.org/">Ruby on Rails</a>. This
  is the sample application for the tutorial.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="http://railstutorial.org/help">Rails Tutorial help page</a>.
  To get help on this sample app, see the
  <a href="http://railstutorial.org/book">Rails Tutorial book</a>.
</p>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>

<div id="banner">
	
	<%= @page_title || "Library" %>
</div>
<% if !current_user %>	
<div class="jumbotron">
      <div class="container">
        <h1>Bem Vindo a Biblioteca Virtual!</h1>
        
         <h1><%= link_to "Crie sua conta!", signup_path %></h1>

         <h3><%= link_to "Ja sou cadastrado", signin_path %></h3>
        
      </div>
    </div>
    <% end %>



<% if current_user %>		
	<div class="row">
		<ul class="thumbnails">
			<%= render @books%>
		</ul>
	</div>
<% end %>