config/routes.rb
Library::Application.routes.draw do

  get "users/new"
  resources :books do
    member do
      post 'lend', controller: 'loans', action: 'lend'
    end
  end

  resources :users
  

  resources :sessions, only: [:new, :create, :destroy]
  resources :loans, only: [:create, :destroy, :index, :update]
  
  root 'static_pages#home'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/signup', to: 'users#new', via: 'get'

  match '/signin', to: 'sessions#new', via: 'get'
  match '/signin', to: 'sessions#create', via: 'post'
  match '/signout', to: 'sessions#destroy', via: 'delete'

match '/search', to: 'books#index', via: 'get'
match '/search_user', to: 'users#index', via: 'get'

  

  

end

app/models/book.rb
class Book < ActiveRecord::Base
	has_many :loans, dependent: :restrict_with_error

#destroy
	#attr_accessible :avatar
	has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
	#has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }
	validates :title, presence: true
	validates :author, presence: true



	def self.search(search, page)
		if search
			paginate :per_page => 5, :page => page,
           :conditions => ['title LIKE ?', "%#{search}%"], :order => 'title'
		else
			paginate :per_page => 5, :page => page
		end
	end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	def new
		@book = Book.new
	end
	def index
		@books = Book.search(params[:search], params[:page])
	end


	def show
		@book = Book.find(params[:id])
		
	end

	def create
		@book = Book.new(book_params)
		if @book.save
			redirect_to @book
			flash[:success] = "Livro adicionado com sucesso!"
		else
			render 'new'
		end
	end

	def destroy
		Book.find(params[:id]).destroy
		flash[:success] = "Book deleted."
		redirect_to :books
	end

	private
	def book_params
		params.require(:book).permit(:title, :author, :gender,
			:edition, :year , :avatar)
	end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
	<div class="span4">
		<div class="thumbnail">
			<%= image_tag book.avatar.url(:medium) %>
			<div class="caption">
				<%= link_to book.title, book %>
			</div>
			<p>	
			<ul>	
				<li><%= button_to "Emprestar", lend_book_path(book), :class => "btn btn-primary", :method => :post  %></li>
	
				<li><% if current_user.admin? %>
					<%= button_to "Deletar",book, :class => "btn btn-default", :method => :delete, data: { confirm: "You sure?" } %>
				<% end %></li>
				</ul> 
			</p>
		
		</div>
	</div>

app/views/books/_form.html.erb
<%= form_for(@book, :html => { :multipart => true }) do |f| %>
 <!--<= render 'shared/error_messages', object: f.object %>-->



 <%= f.label :title %>
 <%= f.text_field :title %>

 <%= f.label :author %>
 <%= f.text_field :author %>

 <%= f.label :gender %>
 <%= f.text_field :gender %>

 <%= f.label :edition %>
 <%= f.text_field :edition %>

 <%= f.label :year %>
 <%= f.date_field :year %>

 <%= f.label :avatar %>
  <%= f.file_field :avatar %>

 
 <%= f.submit id: "submit_book" , class: "btn btn-large btn-primary" %>

 <% end %>

app/views/books/index.html.erb
<% provide(:title, 'All books') %>
<h1>Livros</h1>

<%= will_paginate %>
<div class="row">
	<ul class="thumbnails">
		<%= render @books%>
	</ul>
</div>

<%= will_paginate %>

app/views/books/new.html.erb
<% provide(:title, 'Book') %>
<h1>Novo Livro</h1>

<div class="row">
  <div class="span6 offset3">
   <%= render "form" %>
  </div>
</div>

app/views/books/show.html.erb
<% provide(:title, @book.title) %>
<div class="row">
	<aside class="span4">
		<section>
			<h1>
				<%= image_tag @book.avatar.url() %>
				
			</br>
			
			<%= @book.title %>
		</h1>
		</br>
		<%= @book.author %>
	</br>
	<h4>| <%= link_to "Emprestar", lend_book_path(@book), method: :post %></h4>
	</section>
</aside>

</div>