config/routes.rb
Library::Application.routes.draw do

  get "users/new"
  resources :books do
    member do
      post 'lend', controller: 'loans', action: 'lend'
    end
  end

  resources :users
  

  resources :sessions, only: [:new, :create, :destroy]
  resources :loans, only: [:create, :destroy, :index, :update]
  
  root 'static_pages#home'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/signup', to: 'users#new', via: 'get'

  match '/signin', to: 'sessions#new', via: 'get'
  match '/signin', to: 'sessions#create', via: 'post'
  match '/signout', to: 'sessions#destroy', via: 'delete'

match '/search', to: 'books#index', via: 'get'
match '/search_user', to: 'users#index', via: 'get'

  

  

end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		<a href="http://railstutorial.org/">Rails Tutorial</a>
		by Michael Hartl
	</small>
	<nav>
		<ul>
			<!--<li><%= link_to "About", about_path %></li>-->
			<!--<li>= link_to "Contact", contact_path %></li>-->
			<li><a href="http://news.railstutorial.org/">News</a></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Library", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
           <% if signed_in? %>
              <li><%= link_to "Books", root_path %></li>
              <% else %>
              <li><%= link_to "Home", root_path %></li>
          <% end %>
         
           <% if signed_in? %>
          <li><%= link_to "Loans", loans_path %></li>
          <% end %>
          <% if signed_in? %>
          <% if current_user.admin %>
           <li><%= link_to "Users", users_path %></li>
           <li><%= link_to "New Book", new_book_path %></li>
           <% end %>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_header_admin.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Library", root_path, id: "logo" %>

      <nav>
        <ul class="nav pull-right">


         <% if signed_in? %>
         <li><%= form_tag search_user_path, :method => 'get' ,:class => 'form-search navbar-form'  do %>
           <%= text_field_tag :search, params[:search], class: "input-medium search-query" %>
           <%= submit_tag "Search Users" , class: "btn btn-small" %> 
           <% end %></li>
           
           <li><%= link_to "Books", books_path %></li>
           
           <li><%= link_to "Home", root_path %></li>
           
           <li><%= link_to "Loans", loans_path %></li>
           <li><%= link_to "Users", users_path %></li>
           
           <li><%= link_to "New Book", new_book_path %></li>
           <li id="fat-menu" class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Sign out", signout_path, method: "delete" %>
              </li>
            </ul>
          </li>
          <% else %>
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></
script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title><%= full_title(yield(:title)) %></title>
	<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	<%= csrf_meta_tags %>
	<%= render 'layouts/shim'%>
</head>

<body> 
	   <% if signed_in? && current_user.admin? %>
	      <%= render 'layouts/header_admin' %>
	   <% else %>
	     <%= render 'layouts/header' %>
	   <% end %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
	
	
</body>
</html>